steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/inbound-respect-466416-h0/livecric:latest', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/inbound-respect-466416-h0/livecric:latest']

  -  name: "gcr.io/cloud-builders/gke-deploy"
     args:
     - run
     - --filename=app.yaml
     - --location=us-central1
     - --cluster=autopilot-cluster-1
images:
  - 'gcr.io/inbound-respect-466416-h0/livecric:latest' 